import 'spiritual_gift.dart';
import 'gift_question.dart';

class GiftData {
  static const List<SpiritualGift> allGifts = [
    SpiritualGift(
      id: 'wort_der_weisheit',
      name: 'Wort der Weisheit',
      originalWord: 'λόγος σοφίας (lógos sophías, Gr.); חָכְמָה (chokhmáh, Hebr.)',
      meaning: 'Übernatürliches Wort, das Gottes Plan oder Lösung offenbart',
      bibleReferences: ['1. Kor 12,8', 'Jak 1,5', '1. Kön 3,5-12', 'Ex 31,3', 'Spr 2,6'],
      description: 'Die Gabe des Wortes der Weisheit beschreibt ein vom Heiligen Geist gegebenes Wort oder eine Einsicht, die Gottes Perspektive, Plan oder Lösung für eine konkrete Situation offenbart. Das griechische „logos sophias“ bezeichnet nicht allgemeine Weisheit, sondern ein spezifisches, situationsbezogenes Reden Gottes. In der Bibel zeigt sich diese Gabe z.B. bei Salomo (1. Kön 3), bei den Aposteln in schwierigen Entscheidungen (Apg 6; Apg 15) oder bei Jesus selbst, der göttliche Weisheit in Konfliktsituationen offenbarte. Diese Gabe bringt Klarheit, Orientierung und göttliche Strategie in komplexe Situationen und dient der Leitung und Erbauung der Gemeinde.',
      questions: [
        GiftQuestion(id: 'ww_1', type: QuestionType.experience, text: 'Hast du schon erlebt dass dir in einer schwierigen Situation plötzlich eine klare geistliche Lösung eingefallen ist?'),
        GiftQuestion(id: 'ww_2', type: QuestionType.experience, text: 'Haben Menschen dich schon um Rat gebeten weil sie deine geistliche Einschätzung schätzen?'),
        GiftQuestion(id: 'ww_3', type: QuestionType.experience, text: 'Gab es Situationen in denen du Gottes Perspektive auf ein Problem erkannt hast?'),
        GiftQuestion(id: 'ww_4', type: QuestionType.nature, text: 'Es macht mir Freude Menschen zu helfen gute Entscheidungen vor Gott zu treffen.'),
        GiftQuestion(id: 'ww_5', type: QuestionType.nature, text: 'Ich denke gern darüber nach wie Gottes Prinzipien praktisch angewendet werden können.'),
        GiftQuestion(id: 'ww_6', type: QuestionType.feedback, text: 'Andere sagen mir dass meine Ratschläge ihnen geholfen haben gute Entscheidungen zu treffen.'),
        GiftQuestion(id: 'ww_7', type: QuestionType.feedback, text: 'Meine Einsichten bringen oft Klarheit in schwierige Situationen.'),
      ],
    ),
    SpiritualGift(
      id: 'wort_der_erkenntnis',
      name: 'Wort der Erkenntnis',
      originalWord: 'λόγος γνώσεως (lógos gnóseōs, Gr.)',
      meaning: 'Übernatürliches Wissen oder Einblick in Geheimnisse Gottes',
      bibleReferences: ['1. Kor 12,8', '1. Kor 13,2'],
      description: 'Das Wort der Erkenntnis beschreibt eine vom Heiligen Geist geschenkte Einsicht oder Information über eine Person, Situation oder geistliche Realität, die nicht durch natürliche Erkenntnis gewonnen wurde. Der Begriff „logos gnoseos“ meint eine konkrete Offenbarung von Wissen. In der Bibel zeigt sich diese Gabe etwa bei Petrus, der Ananias’ Täuschung erkennt (Apg 5), oder bei Jesus, der Gedanken und Lebenssituationen von Menschen kennt (Joh 4). Diese Gabe dient dazu, Wahrheit ans Licht zu bringen, Menschen zu helfen und Gottes Wirken sichtbar zu machen.',
      questions: [
        GiftQuestion(id: 'we_1', type: QuestionType.experience, text: 'Hast du schon erlebt dass dir plötzlich ein geistlicher Zusammenhang klar wurde?'),
        GiftQuestion(id: 'we_2', type: QuestionType.experience, text: 'Gab es Momente in denen du Dinge über eine Situation erkannt hast die du vorher nicht wissen konntest?'),
        GiftQuestion(id: 'we_3', type: QuestionType.experience, text: 'Hast du erlebt dass Gott dir besondere Einsichten über Menschen oder Situationen gegeben hat?'),
        GiftQuestion(id: 'we_4', type: QuestionType.nature, text: 'Ich habe Freude daran geistliche Zusammenhänge zu entdecken.'),
        GiftQuestion(id: 'we_5', type: QuestionType.nature, text: 'Ich möchte Gottes Gedanken und Wahrheiten tiefer verstehen.'),
        GiftQuestion(id: 'we_6', type: QuestionType.feedback, text: 'Andere erleben durch meine Einsichten neue Klarheit über geistliche Themen.'),
        GiftQuestion(id: 'we_7', type: QuestionType.feedback, text: 'Menschen sagen dass meine Beobachtungen ihnen helfen Situationen besser zu verstehen.'),
      ],
    ),
    SpiritualGift(
      id: 'glaube',
      name: 'Glaube',
      originalWord: 'πίστις (pístis, Gr.)',
      meaning: 'Besonderer, wundertätiger Glaube, der Berge versetzt',
      bibleReferences: ['1. Kor 12,9', '1. Kor 13,2', 'Mt 17,20', 'Hebr 11'],
      description: 'Die Gabe des Glaubens ist eine besondere, vom Heiligen Geist gewirkte Zuversicht, dass Gott in einer bestimmten Situation handeln wird. Sie geht über den allgemeinen rettenden Glauben hinaus und ist ein übernatürliches Vertrauen auf Gottes Macht und Verheißungen. Das griechische „pistis“ beschreibt hier ein starkes, festes Vertrauen auf Gottes Handeln. In der Bibel zeigt sich diese Gabe bei Personen wie Abraham (Röm 4) oder bei den Aposteln, die mutig Gottes Wirken erwarten. Diese Gabe stärkt andere im Glauben und öffnet Raum für Gottes übernatürliches Eingreifen.',
      questions: [
        GiftQuestion(id: 'gl_1', type: QuestionType.experience, text: 'Hast du erlebt dass du Gott in scheinbar unmöglichen Situationen besonders vertraut hast?'),
        GiftQuestion(id: 'gl_2', type: QuestionType.experience, text: 'Gab es Momente in denen dein Vertrauen auf Gott andere ermutigt hat?'),
        GiftQuestion(id: 'gl_3', type: QuestionType.experience, text: 'Hast du erlebt dass Gott auf dein mutiges Vertrauen hin gehandelt hat?'),
        GiftQuestion(id: 'gl_4', type: QuestionType.nature, text: 'Ich vertraue darauf dass Gott auch große und unmögliche Dinge tun kann.'),
        GiftQuestion(id: 'gl_5', type: QuestionType.nature, text: 'Ich fühle mich motiviert Gott auch dann zu vertrauen wenn andere zweifeln.'),
        GiftQuestion(id: 'gl_6', type: QuestionType.feedback, text: 'Mein Vertrauen auf Gott stärkt häufig den Glauben anderer Menschen.'),
        GiftQuestion(id: 'gl_7', type: QuestionType.feedback, text: 'Menschen sagen dass mein Glaube ihnen Mut macht.'),
      ],
    ),
    SpiritualGift(
      id: 'gaben_der_heilungen',
      name: 'Gaben der Heilungen',
      originalWord: 'χαρίσματα ἰαμάτων (charísmata iamatōn, Gr.)',
      meaning: 'Fähigkeit, Kranke durch Gottes Kraft zu heilen',
      bibleReferences: ['1. Kor 12,9.28.30', 'Jak 5,14-15', 'Mt 10,8', 'Apg 3,1-10', 'Mk 16,18'],
      description: 'Die „Gaben der Heilungen“ beschreiben verschiedene Wirkungen göttlicher Heilung durch den Heiligen Geist. Das griechische „charismata iamaton“ steht im Plural und deutet darauf hin, dass Gott unterschiedliche Arten von Heilungen schenkt – körperlich, seelisch oder geistlich. In der Bibel werden Heilungen durch Jesus und die Apostel häufig beschrieben (z.B. Apg 3; Mk 16). Diese Gabe zeigt Gottes Mitgefühl für leidende Menschen und dient als Zeichen seines Reiches sowie zur Ermutigung des Glaubens.',
      questions: [
        GiftQuestion(id: 'gh_1', type: QuestionType.experience, text: 'Hast du schon erlebt dass jemand nach deinem Gebet körperliche oder seelische Heilung erfahren hat?'),
        GiftQuestion(id: 'gh_2', type: QuestionType.experience, text: 'Hast du häufig den Impuls für kranke Menschen zu beten?'),
        GiftQuestion(id: 'gh_3', type: QuestionType.experience, text: 'Hast du erlebt dass Gott durch Gebet Heilung schenkt?'),
        GiftQuestion(id: 'gh_4', type: QuestionType.nature, text: 'Ich bete gern für kranke oder leidende Menschen.'),
        GiftQuestion(id: 'gh_5', type: QuestionType.nature, text: 'Es bewegt mich wenn Menschen körperlich oder innerlich leiden.'),
        GiftQuestion(id: 'gh_6', type: QuestionType.feedback, text: 'Menschen berichten dass sie durch mein Gebet Trost oder Heilung erfahren haben.'),
        GiftQuestion(id: 'gh_7', type: QuestionType.feedback, text: 'Andere bitten mich gezielt für ihre Gesundheit zu beten.'),
      ],
    ),
    SpiritualGift(
      id: 'wirkungen_von_wundern',
      name: 'Wirkungen von Wundern',
      originalWord: 'ἐνεργήματα δυνάμεων (energémata dynámeōn, Gr.)',
      meaning: 'Vollbringen übernatürlicher Machttaten durch Gottes Kraft',
      bibleReferences: ['1. Kor 12,10.28.29', 'Apg 5,12', '2. Kor 12,12', 'Mk 16,17-18'],
      description: 'Die „Wirkungen von Wundern“ beschreiben übernatürliche Machttaten Gottes, die über natürliche Möglichkeiten hinausgehen. Der Ausdruck „energemata dynameon“ bedeutet wörtlich „wirksame Taten von Macht“. In der Bibel zeigt sich diese Gabe z.B. bei Mose, Elia, Jesus und den Aposteln. Wunder können Befreiung, Versorgung, Naturwunder oder andere außergewöhnliche Eingriffe Gottes sein und bestätigen Gottes Macht und das Evangelium.',
      questions: [
        GiftQuestion(id: 'wwu_1', type: QuestionType.experience, text: 'Hast du Situationen erlebt in denen Gott auf übernatürliche Weise eingegriffen hat?'),
        GiftQuestion(id: 'wwu_2', type: QuestionType.experience, text: 'Hast du erlebt dass Gott durch dein Gebet außergewöhnliche Dinge getan hat?'),
        GiftQuestion(id: 'wwu_3', type: QuestionType.experience, text: 'Gab es Momente in denen Gottes Macht deutlich sichtbar wurde?'),
        GiftQuestion(id: 'wwu_4', type: QuestionType.nature, text: 'Ich glaube dass Gott auch heute noch Wunder tun kann.'),
        GiftQuestion(id: 'wwu_5', type: QuestionType.nature, text: 'Ich bete mutig für Situationen die menschlich unmöglich erscheinen.'),
        GiftQuestion(id: 'wwu_6', type: QuestionType.feedback, text: 'Mein Gebet ermutigt andere mit Gottes Eingreifen zu rechnen.'),
        GiftQuestion(id: 'wwu_7', type: QuestionType.feedback, text: 'Menschen berichten von besonderen Erfahrungen mit Gottes Kraft.'),
      ],
    ),
    SpiritualGift(
      id: 'prophetie',
      name: 'Prophetie',
      originalWord: 'προφητεία (propheteía, Gr.); נְבוּאָה (nevūʾáh, Hebr.)',
      meaning: 'Reden im Auftrag Gottes zur Erbauung, Ermahnung und Tröstung',
      bibleReferences: ['Röm 12,6', '1. Kor 12,10', '1. Kor 14,1-5', '1. Thess 5,20', 'Apg 11,27-28'],
      description: 'Prophetie ist das vom Heiligen Geist inspirierte Reden im Auftrag Gottes zur Erbauung, Ermahnung und Ermutigung der Gemeinde (1. Kor 14,3). Der Begriff „propheteia“ bedeutet wörtlich „für jemanden sprechen“. Prophetie kann sowohl Offenbarung als auch Anwendung von Gottes Wort auf eine konkrete Situation sein. In der Bibel sehen wir prophetisches Reden bei alttestamentlichen Propheten sowie im Neuen Testament z.B. bei Agabus (Apg 11). Diese Gabe stärkt den Glauben, korrigiert Fehlentwicklungen und richtet den Blick der Gemeinde auf Gottes Willen.',
      questions: [
        GiftQuestion(id: 'pr_1', type: QuestionType.experience, text: 'Hast du schon den Eindruck gehabt dass Gott dir ein Wort für eine Person oder Gruppe gibt?'),
        GiftQuestion(id: 'pr_2', type: QuestionType.experience, text: 'Gab es Situationen in denen deine Worte Menschen geistlich aufgebaut haben?'),
        GiftQuestion(id: 'pr_3', type: QuestionType.experience, text: 'Hast du erlebt dass jemand durch deine Worte Gottes Reden erkannt hat?'),
        GiftQuestion(id: 'pr_4', type: QuestionType.nature, text: 'Ich wünsche mir dass Gott durch mich zu anderen Menschen sprechen kann.'),
        GiftQuestion(id: 'pr_5', type: QuestionType.nature, text: 'Ich achte darauf was Gott in einer Situation sagen möchte.'),
        GiftQuestion(id: 'pr_6', type: QuestionType.feedback, text: 'Andere fühlen sich durch meine Worte ermutigt oder gestärkt.'),
        GiftQuestion(id: 'pr_7', type: QuestionType.feedback, text: 'Menschen bestätigen manchmal dass Gott durch meine Worte zu ihnen gesprochen hat.'),
      ],
    ),
    SpiritualGift(
      id: 'unterscheidung_der_geister',
      name: 'Unterscheidung der Geister',
      originalWord: 'διακρίσεις πνευμάτων (diakríseis pneumátōn, Gr.)',
      meaning: 'Unterscheiden zwischen göttlichen, dämonischen und menschlichen Geistern',
      bibleReferences: ['1. Kor 12,10', '1. Joh 4,1', 'Apg 5,3', 'Apg 16,16-18', 'Hebr 5,14'],
      description: 'Die Unterscheidung der Geister ist die Fähigkeit, geistliche Einflüsse zu erkennen und zu unterscheiden, ob sie von Gott, vom menschlichen Geist oder von dämonischen Mächten stammen. Der Begriff „diakrisis pneumaton“ bedeutet „Unterscheidung oder Prüfung von Geistern“. In der Bibel zeigt sich diese Gabe z.B. bei Petrus (Apg 5) oder Paulus (Apg 16). Sie schützt die Gemeinde vor Täuschung und hilft, Gottes Wirken klar zu erkennen.',
      questions: [
        GiftQuestion(id: 'ug_1', type: QuestionType.experience, text: 'Hast du schon gespürt dass hinter einer Situation ein bestimmter geistlicher Einfluss steht?'),
        GiftQuestion(id: 'ug_2', type: QuestionType.experience, text: 'Hast du Situationen erlebt in denen du falsche geistliche Einflüsse erkannt hast?'),
        GiftQuestion(id: 'ug_3', type: QuestionType.experience, text: 'Hast du erlebt dass du geistlich beurteilen konntest ob etwas von Gott ist?'),
        GiftQuestion(id: 'ug_4', type: QuestionType.nature, text: 'Ich möchte verstehen welche geistlichen Kräfte in einer Situation wirken.'),
        GiftQuestion(id: 'ug_5', type: QuestionType.nature, text: 'Ich prüfe geistliche Eindrücke sorgfältig.'),
        GiftQuestion(id: 'ug_6', type: QuestionType.feedback, text: 'Andere fragen mich manchmal nach meiner geistlichen Einschätzung.'),
        GiftQuestion(id: 'ug_7', type: QuestionType.feedback, text: 'Meine Einschätzung hilft manchmal Fehlentwicklungen zu erkennen.'),
      ],
    ),
    SpiritualGift(
      id: 'arten_von_zungen',
      name: 'Arten von Zungen',
      originalWord: 'γένη γλωσσῶν (génē glōssōn, Gr.)',
      meaning: 'Reden in anderen Sprachen oder in der Gebetssprache des Geistes',
      bibleReferences: ['1. Kor 12,10.28.30', '1. Kor 14', 'Apg 2,4-11', 'Apg 19,6', 'Mk 16,17'],
      description: 'Die Gabe der Zungenrede beschreibt das vom Heiligen Geist inspirierte Sprechen in einer Sprache, die der Sprecher nicht gelernt hat. Das griechische „gene glosson“ bedeutet „verschiedene Arten von Sprachen“. In der Bibel erscheint diese Gabe erstmals zu Pfingsten (Apg 2) und wird besonders in 1. Korinther 12–14 erklärt. Sie kann sowohl als persönliche Gebetssprache als auch als öffentliches Zeichen für Gottes Wirken dienen.',
      questions: [
        GiftQuestion(id: 'az_1', type: QuestionType.experience, text: 'Hast du erlebt dass du in einer geistlichen Gebetssprache betest?'),
        GiftQuestion(id: 'az_2', type: QuestionType.experience, text: 'Hast du Situationen erlebt in denen du in einer anderen Sprache gebetet hast?'),
        GiftQuestion(id: 'az_3', type: QuestionType.experience, text: 'Hast du erfahren dass Zungengebet dich im Glauben stärkt?'),
        GiftQuestion(id: 'az_4', type: QuestionType.nature, text: 'Ich bete gern spontan und frei im Gebet.'),
        GiftQuestion(id: 'az_5', type: QuestionType.nature, text: 'Ich bin offen für übernatürliche Ausdrucksformen im Gebet.'),
        GiftQuestion(id: 'az_6', type: QuestionType.feedback, text: 'Mein Gebetsleben wird durch geistliches Beten gestärkt.'),
        GiftQuestion(id: 'az_7', type: QuestionType.feedback, text: 'Andere erleben mein Gebet als geistlich ermutigend.'),
      ],
    ),
    SpiritualGift(
      id: 'auslegung_der_zungen',
      name: 'Auslegung der Zungen',
      originalWord: 'ἑρμηνεία γλωσσῶν (hermēneía glōssōn, Gr.)',
      meaning: 'Deuten und Übersetzen der Zungenrede zur Erbauung der Gemeinde',
      bibleReferences: ['1. Kor 12,10', '1. Kor 14,13.27-28'],
      description: 'Die Auslegung der Zungen ist die Fähigkeit, eine Zungenrede zu verstehen und für andere verständlich zu machen. Das griechische „hermeneia glosson“ bedeutet „Übersetzung oder Deutung von Sprachen“. Diese Gabe sorgt dafür, dass eine Zungenrede in der Gemeinde zur Erbauung dient, indem ihre Bedeutung verständlich wird (1. Kor 14).',
      questions: [
        GiftQuestion(id: 'au_1', type: QuestionType.experience, text: 'Hast du schon einmal eine Zungenrede verstanden oder erklären können?'),
        GiftQuestion(id: 'au_2', type: QuestionType.experience, text: 'Hast du erlebt dass dir die Bedeutung eines geistlichen Gebets klar wurde?'),
        GiftQuestion(id: 'au_3', type: QuestionType.experience, text: 'Hast du erlebt dass Gott dir geholfen hat geistliche Botschaften zu verstehen?'),
        GiftQuestion(id: 'au_4', type: QuestionType.nature, text: 'Ich wünsche mir geistliche Botschaften verständlich zu machen.'),
        GiftQuestion(id: 'au_5', type: QuestionType.nature, text: 'Ich habe Freude daran geistliche Eindrücke zu deuten.'),
        GiftQuestion(id: 'au_6', type: QuestionType.feedback, text: 'Andere werden durch meine Erklärung geistlicher Botschaften aufgebaut.'),
        GiftQuestion(id: 'au_7', type: QuestionType.feedback, text: 'Menschen verstehen geistliche Inhalte durch meine Erklärungen besser.'),
      ],
    ),
    SpiritualGift(
      id: 'dienst_diakonie',
      name: 'Dienst / Diakonie',
      originalWord: 'διακονία (diakonía, Gr.)',
      meaning: 'Praktisches Dienen und Helfen in der Gemeinde',
      bibleReferences: ['Röm 12,7', '1. Kor 12,28', 'Apg 6,1-7', '1. Petr 4,10-11'],
      description: 'Die Gabe des Dienstes beschreibt eine besondere Befähigung, anderen praktisch zu helfen und Bedürfnisse zu erkennen. Das griechische „diakonia“ bedeutet „Dienst“ oder „praktische Hilfe“. In der Bibel zeigt sich diese Gabe besonders im Dienst der ersten Diakone (Apg 6). Menschen mit dieser Gabe tragen wesentlich dazu bei, dass die Gemeinde praktisch funktioniert und Menschen konkrete Hilfe erfahren.',
      questions: [
        GiftQuestion(id: 'di_1', type: QuestionType.experience, text: 'Hast du oft erlebt dass du praktische Aufgaben übernommen hast um anderen zu helfen?'),
        GiftQuestion(id: 'di_2', type: QuestionType.experience, text: 'Gab es Situationen in denen du spontan geholfen hast?'),
        GiftQuestion(id: 'di_3', type: QuestionType.experience, text: 'Hast du erlebt dass dein praktischer Einsatz anderen sehr geholfen hat?'),
        GiftQuestion(id: 'di_4', type: QuestionType.nature, text: 'Ich habe Freude daran praktisch zu helfen.'),
        GiftQuestion(id: 'di_5', type: QuestionType.nature, text: 'Ich sehe schnell wo Hilfe gebraucht wird.'),
        GiftQuestion(id: 'di_6', type: QuestionType.feedback, text: 'Andere fühlen sich durch meine Hilfe unterstützt.'),
        GiftQuestion(id: 'di_7', type: QuestionType.feedback, text: 'Mein Einsatz hilft dass Dinge gut funktionieren.'),
      ],
    ),
    SpiritualGift(
      id: 'lehren',
      name: 'Lehren',
      originalWord: 'διδασκαλία (didaskalía, Gr.)',
      meaning: 'Unterweisen in der Wahrheit Gottes',
      bibleReferences: ['Röm 12,7', 'Eph 4,11', '1. Tim 3,2', '2. Tim 2,2'],
      description: 'Die Gabe des Lehrens ist die Fähigkeit, Gottes Wort klar, verständlich und treu zu erklären. Der Begriff „didaskalia“ bezeichnet sowohl den Inhalt als auch die Tätigkeit des Lehrens. In der Bibel wird diese Gabe besonders mit Leitungsaufgaben verbunden (Eph 4,11). Sie hilft der Gemeinde, Gottes Wahrheit zu verstehen und im Glauben zu wachsen.',
      questions: [
        GiftQuestion(id: 'le_1', type: QuestionType.experience, text: 'Hast du schon erlebt dass andere durch deine Erklärung etwas besser verstanden haben?'),
        GiftQuestion(id: 'le_2', type: QuestionType.experience, text: 'Hast du öfter Bibeltexte oder Themen erklärt?'),
        GiftQuestion(id: 'le_3', type: QuestionType.experience, text: 'Hast du erlebt dass Menschen durch deine Erklärung geistlich gewachsen sind?'),
        GiftQuestion(id: 'le_4', type: QuestionType.nature, text: 'Ich beschäftige mich gern intensiv mit der Bibel.'),
        GiftQuestion(id: 'le_5', type: QuestionType.nature, text: 'Ich erkläre anderen gern was ich gelernt habe.'),
        GiftQuestion(id: 'le_6', type: QuestionType.feedback, text: 'Andere sagen dass sie durch mich Dinge besser verstehen.'),
        GiftQuestion(id: 'le_7', type: QuestionType.feedback, text: 'Menschen wachsen im Glauben durch meine Erklärungen.'),
      ],
    ),
    SpiritualGift(
      id: 'ermahnung',
      name: 'Ermahnung / Zuspruch',
      originalWord: 'παράκλησις (paráklēsis, Gr.)',
      meaning: 'Ermutigen, Trösten und Ermahnen',
      bibleReferences: ['Röm 12,8', '1. Kor 14,3'],
      description: 'Die Gabe der Ermutigung oder Ermahnung („paraklesis“) beschreibt die Fähigkeit, Menschen durch Worte zu stärken, zu trösten und zum Glauben zu ermutigen. Das Wort steht in Verbindung mit dem Begriff „Paraklet“, der für den Heiligen Geist als Tröster verwendet wird. Diese Gabe hilft Menschen, schwierige Zeiten zu überwinden und im Glauben weiterzugehen.',
      questions: [
        GiftQuestion(id: 'er_1', type: QuestionType.experience, text: 'Hast du erlebt dass du Menschen ermutigt hast weiterzugehen?'),
        GiftQuestion(id: 'er_2', type: QuestionType.experience, text: 'Hast du Situationen erlebt in denen deine Worte Trost gegeben haben?'),
        GiftQuestion(id: 'er_3', type: QuestionType.experience, text: 'Hast du erlebt dass jemand durch deine Ermutigung neue Hoffnung bekam?'),
        GiftQuestion(id: 'er_4', type: QuestionType.nature, text: 'Ich habe Freude daran Menschen zu ermutigen.'),
        GiftQuestion(id: 'er_5', type: QuestionType.nature, text: 'Ich merke schnell wenn jemand Ermutigung braucht.'),
        GiftQuestion(id: 'er_6', type: QuestionType.feedback, text: 'Andere fühlen sich nach Gesprächen mit mir gestärkt.'),
        GiftQuestion(id: 'er_7', type: QuestionType.feedback, text: 'Menschen sagen dass meine Worte ihnen Hoffnung geben.'),
      ],
    ),
    SpiritualGift(
      id: 'geben',
      name: 'Geben',
      originalWord: 'μεταδιδόναι (metadidónai, Gr.)',
      meaning: 'Großzügiges, freudiges Geben mit Einfalt',
      bibleReferences: ['Röm 12,8', 'Apg 4,32-37', '2. Kor 8–9'],
      description: 'Die Gabe des Gebens beschreibt eine besondere Bereitschaft und Freude, materielle oder finanzielle Ressourcen großzügig weiterzugeben. Das griechische „metadidonai“ bedeutet „teilen“ oder „weitergeben“. In der Bibel sehen wir Beispiele dafür in der frühen Gemeinde (Apg 4). Diese Gabe macht Gottes Versorgung sichtbar und unterstützt die Arbeit des Reiches Gottes.',
      questions: [
        GiftQuestion(id: 'ge_1', type: QuestionType.experience, text: 'Hast du erlebt dass du gern großzügig gegeben hast?'),
        GiftQuestion(id: 'ge_2', type: QuestionType.experience, text: 'Hast du Situationen erlebt in denen du bewusst auf eigene Dinge verzichtet hast um anderen zu helfen?'),
        GiftQuestion(id: 'ge_3', type: QuestionType.experience, text: 'Hast du erlebt dass Gott dich segnet wenn du großzügig gibst?'),
        GiftQuestion(id: 'ge_4', type: QuestionType.nature, text: 'Ich gebe gern von meinen Ressourcen weiter.'),
        GiftQuestion(id: 'ge_5', type: QuestionType.nature, text: 'Es macht mir Freude andere finanziell oder materiell zu unterstützen.'),
        GiftQuestion(id: 'ge_6', type: QuestionType.feedback, text: 'Mein Geben ermöglicht anderen wichtige Dinge.'),
        GiftQuestion(id: 'ge_7', type: QuestionType.feedback, text: 'Andere erleben meine Großzügigkeit als Segen.'),
      ],
    ),
    SpiritualGift(
      id: 'leiten',
      name: 'Leiten / Verwalten',
      originalWord: 'προϊστάμενος (proistámenos, Gr.)',
      meaning: 'Führen und Organisieren der Gemeinde (wie ein Steuermann)',
      bibleReferences: ['Röm 12,8', '1. Kor 12,28', '1. Thess 5,12', '1. Tim 5,17'],
      description: 'Die Gabe der Leitung beschreibt die Fähigkeit, Menschen zu führen, Vision zu vermitteln und Strukturen zu organisieren. Das griechische Wort „proistamenos“ bedeutet „vorstehen“ oder „leiten“. In der Bibel wird diese Gabe mit Verantwortung für die Gemeinde verbunden (1. Thess 5). Sie hilft, dass Dienste koordiniert werden und die Gemeinde gemeinsam vorankommt.',
      questions: [
        GiftQuestion(id: 'lei_1', type: QuestionType.experience, text: 'Hast du erlebt dass du Gruppen organisiert oder geleitet hast?'),
        GiftQuestion(id: 'lei_2', type: QuestionType.experience, text: 'Haben Menschen dir Verantwortung übertragen?'),
        GiftQuestion(id: 'lei_3', type: QuestionType.experience, text: 'Hast du erlebt dass du Projekte oder Teams erfolgreich koordinieren konntest?'),
        GiftQuestion(id: 'lei_4', type: QuestionType.nature, text: 'Ich übernehme gern Verantwortung.'),
        GiftQuestion(id: 'lei_5', type: QuestionType.nature, text: 'Ich denke gern strategisch über Abläufe und Organisation nach.'),
        GiftQuestion(id: 'lei_6', type: QuestionType.feedback, text: 'Menschen folgen gern meiner Leitung.'),
        GiftQuestion(id: 'lei_7', type: QuestionType.feedback, text: 'Unter meiner Leitung werden Ziele gut erreicht.'),
      ],
    ),
    SpiritualGift(
      id: 'barmherzigkeit',
      name: 'Barmherzigkeit',
      originalWord: 'ἔλεος (éleos, Gr.)',
      meaning: 'Mitgefühl und praktische Hilfe für Leidende',
      bibleReferences: ['Röm 12,8', 'Mt 5,7', 'Gal 6,2'],
      description: 'Die Gabe der Barmherzigkeit beschreibt ein besonderes Mitgefühl für Menschen in Not und die Bereitschaft, ihnen praktisch zu helfen. Das griechische „eleos“ bedeutet „Erbarmen“ oder „Mitgefühl“. In der Bibel wird Barmherzigkeit als Ausdruck von Gottes Charakter beschrieben (Mt 5,7). Menschen mit dieser Gabe bringen Gottes Liebe besonders zu leidenden Menschen.',
      questions: [
        GiftQuestion(id: 'ba_1', type: QuestionType.experience, text: 'Hast du oft mit Menschen mitgefühlt die leiden?'),
        GiftQuestion(id: 'ba_2', type: QuestionType.experience, text: 'Hast du erlebt dass du dich besonders um Bedürftige kümmerst?'),
        GiftQuestion(id: 'ba_3', type: QuestionType.experience, text: 'Hast du Menschen in schweren Zeiten begleitet?'),
        GiftQuestion(id: 'ba_4', type: QuestionType.nature, text: 'Es macht mir Freude Menschen praktisch und emotional zu helfen.'),
        GiftQuestion(id: 'ba_5', type: QuestionType.nature, text: 'Ich möchte Menschen praktisch und emotional helfen.'),
        GiftQuestion(id: 'ba_6', type: QuestionType.feedback, text: 'Menschen fühlen sich durch mich verstanden.'),
        GiftQuestion(id: 'ba_7', type: QuestionType.feedback, text: 'Andere erleben durch mich Trost und Unterstützung.'),
      ],
    ),
    SpiritualGift(
      id: 'apostel',
      name: 'Apostelamt',
      originalWord: 'ἀπόστολος (apóstolos, Gr.)',
      meaning: 'Gesandtsein mit Vollmacht zum Gründen von Gemeinden',
      bibleReferences: ['1. Kor 12,28', 'Eph 4,11', 'Apg 1,21-26', 'Apg 14,14'],
      description: 'Die Gabe des Apostels beschreibt eine besondere Berufung, neue Werke oder Gemeinden zu gründen und geistliche Bewegungen zu initiieren. Das Wort „apostolos“ bedeutet „Gesandter“. In der Bibel sehen wir diese Gabe bei den Aposteln, die das Evangelium verbreiteten und Gemeinden gründeten. Diese Gabe verbindet Vision, Leitung und missionarische Dynamik.',
      questions: [
        GiftQuestion(id: 'ap_1', type: QuestionType.experience, text: 'Hast du erlebt dass du neue Initiativen oder Dienste gestartet hast?'),
        GiftQuestion(id: 'ap_2', type: QuestionType.experience, text: 'Hast du schon geholfen neue Gemeinden oder Gruppen aufzubauen?'),
        GiftQuestion(id: 'ap_3', type: QuestionType.experience, text: 'Hast du Menschen mobilisiert neue geistliche Werke zu beginnen?'),
        GiftQuestion(id: 'ap_4', type: QuestionType.nature, text: 'Ich habe eine Vision neue Dinge im Reich Gottes zu starten.'),
        GiftQuestion(id: 'ap_5', type: QuestionType.nature, text: 'Ich denke gern strategisch über Wachstum der Gemeinde nach.'),
        GiftQuestion(id: 'ap_6', type: QuestionType.feedback, text: 'Neue Dienste entstehen oft durch meine Initiative.'),
        GiftQuestion(id: 'ap_7', type: QuestionType.feedback, text: 'Menschen schließen sich Visionen an die ich starte.'),
      ],
    ),
    SpiritualGift(
      id: 'evangelist',
      name: 'Evangelist',
      originalWord: 'εὐαγγελιστής (euangelistḗs, Gr.)',
      meaning: 'Verkündigen der guten Botschaft (Evangelium)',
      bibleReferences: ['Eph 4,11', 'Apg 21,8', '2. Tim 4,5'],
      description: 'Die Gabe des Evangelisten ist die besondere Fähigkeit, Menschen die gute Nachricht von Jesus verständlich und überzeugend zu vermitteln. Das Wort „euangelistes“ bedeutet „Verkündiger der guten Nachricht“. In der Bibel sehen wir diese Gabe z.B. bei Philippus (Apg 21). Evangelisten helfen Menschen, zum Glauben an Christus zu kommen.',
      questions: [
        GiftQuestion(id: 'ev_1', type: QuestionType.experience, text: 'Hast du oft mit Menschen über deinen Glauben gesprochen?'),
        GiftQuestion(id: 'ev_2', type: QuestionType.experience, text: 'Hast du erlebt dass Menschen durch dein Zeugnis Interesse an Jesus bekommen?'),
        GiftQuestion(id: 'ev_3', type: QuestionType.experience, text: 'Hast du erlebt dass Menschen durch dich zum Glauben gekommen sind?'),
        GiftQuestion(id: 'ev_4', type: QuestionType.nature, text: 'Ich rede gern mit Menschen über Jesus.'),
        GiftQuestion(id: 'ev_5', type: QuestionType.nature, text: 'Ich suche aktiv Möglichkeiten meinen Glauben zu teilen.'),
        GiftQuestion(id: 'ev_6', type: QuestionType.feedback, text: 'Menschen reagieren offen wenn ich von meinem Glauben erzähle.'),
        GiftQuestion(id: 'ev_7', type: QuestionType.feedback, text: 'Mein Zeugnis führt andere näher zu Jesus.'),
      ],
    ),
    SpiritualGift(
      id: 'hirte',
      name: 'Hirte / Pastor',
      originalWord: 'ποιμήν (poimḗn, Gr.)',
      meaning: 'Weiden, Hüten und Versorgen der Gemeinde als Herde',
      bibleReferences: ['Eph 4,11', 'Joh 10,1-18', '1. Petr 5,1-4'],
      description: 'Die Gabe des Hirten beschreibt die Fähigkeit, Menschen geistlich zu begleiten, zu schützen und zu fördern. Das griechische „poimen“ bedeutet „Hirte“. Jesus selbst wird als der gute Hirte beschrieben (Joh 10). Menschen mit dieser Gabe kümmern sich langfristig um das geistliche Wachstum und das Wohl der Gemeinde.',
      questions: [
        GiftQuestion(id: 'hi_1', type: QuestionType.experience, text: 'Hast du Menschen über längere Zeit geistlich begleitet?'),
        GiftQuestion(id: 'hi_2', type: QuestionType.experience, text: 'Hast du erlebt dass du Verantwortung für das geistliche Wohl anderer trägst?'),
        GiftQuestion(id: 'hi_3', type: QuestionType.experience, text: 'Hast du Menschen geholfen im Glauben zu wachsen?'),
        GiftQuestion(id: 'hi_4', type: QuestionType.nature, text: 'Ich kümmere mich gern um Menschen und ihre Entwicklung.'),
        GiftQuestion(id: 'hi_5', type: QuestionType.nature, text: 'Ich fühle mich verantwortlich für das geistliche Wohl anderer.'),
        GiftQuestion(id: 'hi_6', type: QuestionType.feedback, text: 'Menschen fühlen sich durch mich begleitet und unterstützt.'),
        GiftQuestion(id: 'hi_7', type: QuestionType.feedback, text: 'Andere wachsen im Glauben durch meine Begleitung.'),
      ],
    ),
  ];
}
